version: '3.0'

services:

  go-server-app:
    build:
      context: .
    ports:
      - "28080:28080"

  collector:
    image: otel/opentelemetry-collector:latest
    container_name: app-collector
    hostname: collector
    command: [ "--config=/etc/collector-config.yaml" ]
    volumes:
      - ./collector-config.yaml:/etc/collector-config.yaml
    ports:
      - "5555:5555"
      - "6666:6666"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.39.2
    container_name: app-prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./observability-backend/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/status || exit 1

  grafana:
    image: grafana/grafana:latest
    container_name: app-grafana
    hostname: grafana
    depends_on:
      - prometheus
    volumes:
      - ./observability-backend/grafana-bootstrap.ini:/etc/grafana/grafana.ini
      - ./observability-backend/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1