global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'collector'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'collector:6666' ]
    tls_config:
      insecure_skip_verify: true
